check:
    global:
        statements: 0
        lines: 0
        branches: 0
        functions: 0
        excludes: []
    each:
        statements: 0
        lines: 0
        branches: 0
        functions: 0
        excludes: []
reporting:
    watermarks:
        statements: [15, 80]
        lines: [15, 80]
        functions: [15, 80]
        branches: [15, 80]
